  services:                                                                                                                                                                                                                                                                
    db:           
      image: postgres:16
      environment:
        - POSTGRES_DB=food_coster
        - POSTGRES_USER=food_coster
        - POSTGRES_PASSWORD=food_coster
      ports:                                                                                                                                                                                                                                                               
        - 5442:5432
      volumes:                                                                                                                                                                                                                                                             
        - postgres_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
        interval: 5s                                                                                                                                                                                                                                                       
        timeout: 5s
        retries: 5                                                                                                                                                                                                                                                         
                  
  volumes:
    postgres_data: